name: Build and deploy PHP app to Azure Web App - webcosmeticmethod2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Chỉ định phiên bản Ubuntu

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
     
      # Run PHP lint check
      - name: Run PHP lint check
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

      # Check if composer.json exists
      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      # Install Composer Dependencies
      - name: Install Composer Dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          composer validate --no-check-publish || exit 0
          composer install --prefer-dist --no-progress --no-suggest

      # Install PHPUnit and Run Tests
      - name: Install PHPUnit and Run Tests
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          composer require --dev phpunit/phpunit ^9.5
          if [ -f "vendor/bin/phpunit" ]; then
            vendor/bin/phpunit --testdox || exit 0
          else
            echo "PHPUnit not found, skipping tests."
          fi

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'webcosmeticmethod2'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9158C6D45057436AA28FC55BD1044547 }}
